import { env } from "../../config/env.js";

export const POLICY_CONFIG = {
  POLICY_ID: "POL_FINTECH_RECOVER_V1",
  MAX_RETRIES: env.POLICY_MAX_RETRIES,
  MAX_DISCOUNT_PERCENT: env.POLICY_MAX_DISCOUNT_PERCENT,
  MIN_AI_CONFIDENCE: 0.7,
};
