export enum FSMStateEnum {
  FAILED = "FAILED",
  DIAGNOSING = "DIAGNOSING",
  DIAGNOSED = "DIAGNOSED",
  ACTION_AUTHORIZED = "ACTION_AUTHORIZED",
  AWAITING_PAYMENT = "AWAITING_PAYMENT",
  P2P_PAUSED = "P2P_PAUSED",
  PAID = "PAID",
  HALTED = "HALTED",
  ESCALATED = "ESCALATED",
  POLICY_BLOCKED = "POLICY_BLOCKED",
  TERMINATED_OPT_OUT = "TERMINATED_OPT_OUT"
}

export enum CustomerTierEnum {
  STANDARD = "STANDARD",
  ENTERPRISE = "ENTERPRISE"
}

export enum SubscriptionStatusEnum {
  ACTIVE = "ACTIVE",
  HALTED = "HALTED",
  CANCELLED = "CANCELLED"
}

export enum DecisionTypeEnum {
  ALLOW = "ALLOW",
  DENY = "DENY"
}
